apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: scum-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      kind: scum
  template:
    metadata:
      labels:
        kind: scum
    spec:
      containers:
        - name: scum-pod
          image: ihippik/k8s-scum:main
          args: [ "server" ]